stages:
  - configure
  - buildlibs
  - buildtests
  - test

variables:
  C_COMPILER: /llvm/llvm-project/build/bin/clang
  CXX_COMPILER: /llvm/llvm-project/build/bin/clang++
  CMAKE_RELEASE: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER ..
  CMAKE_DEBUG: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER ..

compile:Exceptions:release:
  stage: buildlibs
  script:
    - mkdir build
    - cd build
    - eval $CMAKE_RELEASE
    - make -j $(nproc) RogueLib_Exceptions

compile:Exceptions:debug:
  stage: buildlibs
  script:
    - mkdir build
    - cd build
    - eval $CMAKE_DEBUG
    - make -j $(nproc) RogueLib_Exceptions


compile:Logging:release:
  stage: buildlibs
  script:
    - mkdir build
    - cd build
    - eval $CMAKE_RELEASE
    - make -j $(nproc) RogueLib_Logging

compile:Logging:debug:
  stage: buildlibs
  script:
    - mkdir build
    - cd build
    - eval $CMAKE_DEBUG
    - make -j $(nproc) RogueLib_Logging

compile:Networking:release:
  stage: buildlibs
  script:
    - mkdir build
    - cd build
    - eval $CMAKE_RELEASE
    - make -j $(nproc) RogueLib_Networking

compile:Networking:debug:
  stage: buildlibs
  script:
    - mkdir build
    - cd build
    - eval $CMAKE_DEBUG
    - make -j $(nproc) RogueLib_Networking

compile:Scripting:release:
  stage: buildlibs
  script:
    - chmod +x $(find ./RogueLib -name *.sh)
    - mkdir build
    - cd build
    - eval $CMAKE_RELEASE
    - make -j $(nproc) RogueLib_Scripting

compile:Scripting:debug:
  stage: buildlibs
  script:
    - chmod +x $(find ./RogueLib -name *.sh)
    - mkdir build
    - cd build
    - eval $CMAKE_DEBUG
    - make -j $(nproc) RogueLib_Scripting

compile:Threading:release:
  stage: buildlibs
  script:
    - mkdir build
    - cd build
    - eval $CMAKE_RELEASE
    - make -j $(nproc) RogueLib_Threading

compile:Threading:debug:
  stage: buildlibs
  script:
    - mkdir build
    - cd build
    - eval $CMAKE_DEBUG
    - make -j $(nproc) RogueLib_Threading
