stages:
  - configure
  - build
  - test

configure:
  stage: configure
  before_script:
      - chmod +x gitlab-ci/*
      - git submodule update --init --recursive
  script: "gitlab-ci/configure.sh"

build:
  stage: build
  before_script:
    - chmod +x gitlab-ci/*
  script: "gitlab-ci/build.sh"