stages:
  - buildboost
  - configure
  - buildlibs
  - buildtests
  - test

boost:
  stage: buildboost
  script:
    - echo

variables:
  C_COMPILER: /llvm/llvm-project/build/bin/clang
  CXX_COMPILER: /llvm/llvm-project/build/bin/clang++
  CMAKE_COMMAND:  cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPU -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER ..

compile:Exceptions:release:
  stage: buildlibs
  script:
    - export BUILD_TYPE=Release
    - mkdir build
    - cd build
    - eval $CMAKE_COMMAND
    - make -j $(nproc) RogueLib_Exceptions

compile:Exceptions:debug:
  stage: buildlibs
  script:
    - export BUILD_TYPE=Debug
    - mkdir build
    - cd build
    - eval $CMAKE_COMMAND
    - make -j $(nproc) RogueLib_Exceptions


compile:Logging:release:
  stage: buildlibs
  script:
    - export BUILD_TYPE=Release
    - mkdir build
    - cd build
    - eval $CMAKE_COMMAND
    - make -j $(nproc) RogueLib_Logging

compile:Logging:debug:
  stage: buildlibs
  script:
    - export BUILD_TYPE=Debug
    - mkdir build
    - cd build
    - eval $CMAKE_COMMAND
    - make -j $(nproc) RogueLib_Logging

compile:Networking:release:
  stage: buildlibs
  script:
    - export BUILD_TYPE=Release
    - mkdir build
    - cd build
    - make -j $(nproc) RogueLib_Networking

compile:Networking:debug:
  stage: buildlibs
  script:
    - export BUILD_TYPE=Debug
    - mkdir build
    - cd build
    - eval $CMAKE_COMMAND
    - make -j $(nproc) RogueLib_Networking

compile:Scripting:release:
  stage: buildlibs
  script:
    - export BUILD_TYPE=Release
    - chmod +x $(find ./RogueLib -name *.sh)
    - mkdir build
    - cd build
    - eval $CMAKE_COMMAND
    - make -j $(nproc) RogueLib_Scripting

compile:Scripting:debug:
  stage: buildlibs
  script:
    - export BUILD_TYPE=Debug
    - chmod +x $(find ./RogueLib -name *.sh)
    - mkdir build
    - cd build
    - eval $CMAKE_COMMAND
    - make -j $(nproc) RogueLib_Scripting

compile:Threading:release:
  stage: buildlibs
  script:
    - export BUILD_TYPE=Release
    - mkdir build
    - cd build
    - eval $CMAKE_COMMAND
    - make -j $(nproc) RogueLib_Threading

compile:Threading:debug:
  stage: buildlibs
  script:
    - export BUILD_TYPE=Debug
    - mkdir build
    - cd build
    - eval $CMAKE_COMMAND
    - make -j $(nproc) RogueLib_Threading
